branches:
  only:
  - evolution
  - develop
  - /^feature-.*$/
language: php
php:
- 5.3
notifications:
  email: false
addons:
  sauce_connect:
    username:
      secure: "B9VRUWYj0GeV3bqiR6Pzs89LVwuYgrsXCeUeIY6D6YPfceD+OgjsgnuescDdUXOA12CUt075iP37IXuWOHVesx3T8BOQllltu/mXoi/tubOAnjAzaqHbgCvbSHjltTHAmZWqlghUu1jEJBHmVjV6qyq/fWPiyUL83xvv8esgod8="
    access_key:
      secure: "Y0lQJ4iR8X17+hcAA3K3FaZAenX09phbBibLZg3ey+OPCloLe3Rbvjl3Gfk2CfZP/utK6jnjFcEY71mqxmdDxE0KBECfx5ORp0OzGDODaAE9qAzqWwsS6DlGv0t6X8B31S9GyBJVBdL28ALkJYyKxANI0UTXUmavzlrSaIGzL80="
before_script:
- mysql -e 'create database ip_test;'
- sed -e 's/\[\[\[\[database\]\]\]\]/ip_test/g' < install/sql/structure.sql | sed
  -e 's/`ip_cms_/`ip_/g' | mysql -D ip_test
- sed -e 's/`ip_cms_/`ip_/g' < install/sql/data.sql | mysql -D ip_test
- cd phpunit
- sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"`
  = "1" ]; then ./travis-nginx-install.sh; fi"
script: ./vendor/bin/phpunit --group Sauce --colors Tests/